// @generated by protoc-gen-connect-es v1.1.3 with parameter "target=ts"
// @generated from file proto/com/qapp/hermes/hermes.proto (package com.qapp.hermes, syntax proto3)
/* eslint-disable */
// @ts-nocheck

/**
 * @generated from service com.qapp.hermes.Hermes
 */
export const Hermes = {
  typeName: "com.qapp.hermes.Hermes",
  methods: {
  }
} as const;

