// @generated by protoc-gen-es v1.4.1 with parameter "target=ts"
// @generated from file proto/com/qapp/hermes/hermes.proto (package com.qapp.hermes, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message, proto3 } from "@bufbuild/protobuf";

/**
 * @generated from message com.qapp.hermes.TopupCreditsRequest
 */
export class TopupCreditsRequest extends Message<TopupCreditsRequest> {
  /**
   * @generated from field: int32 user_id = 1;
   */
  userId = 0;

  /**
   * @generated from field: int32 amount = 2;
   */
  amount = 0;

  constructor(data?: PartialMessage<TopupCreditsRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "com.qapp.hermes.TopupCreditsRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "user_id", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 2, name: "amount", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): TopupCreditsRequest {
    return new TopupCreditsRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): TopupCreditsRequest {
    return new TopupCreditsRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): TopupCreditsRequest {
    return new TopupCreditsRequest().fromJsonString(jsonString, options);
  }

  static equals(a: TopupCreditsRequest | PlainMessage<TopupCreditsRequest> | undefined, b: TopupCreditsRequest | PlainMessage<TopupCreditsRequest> | undefined): boolean {
    return proto3.util.equals(TopupCreditsRequest, a, b);
  }
}

/**
 * @generated from message com.qapp.hermes.CreditsOperationResponse
 */
export class CreditsOperationResponse extends Message<CreditsOperationResponse> {
  /**
   * @generated from field: int32 user_id = 1;
   */
  userId = 0;

  /**
   * @generated from field: int32 old_balance = 2;
   */
  oldBalance = 0;

  /**
   * @generated from field: int32 new_balance = 3;
   */
  newBalance = 0;

  constructor(data?: PartialMessage<CreditsOperationResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "com.qapp.hermes.CreditsOperationResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "user_id", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 2, name: "old_balance", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 3, name: "new_balance", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): CreditsOperationResponse {
    return new CreditsOperationResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): CreditsOperationResponse {
    return new CreditsOperationResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): CreditsOperationResponse {
    return new CreditsOperationResponse().fromJsonString(jsonString, options);
  }

  static equals(a: CreditsOperationResponse | PlainMessage<CreditsOperationResponse> | undefined, b: CreditsOperationResponse | PlainMessage<CreditsOperationResponse> | undefined): boolean {
    return proto3.util.equals(CreditsOperationResponse, a, b);
  }
}

/**
 * @generated from message com.qapp.hermes.GetCreditsRequest
 */
export class GetCreditsRequest extends Message<GetCreditsRequest> {
  /**
   * @generated from field: int32 user_id = 1;
   */
  userId = 0;

  constructor(data?: PartialMessage<GetCreditsRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "com.qapp.hermes.GetCreditsRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "user_id", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GetCreditsRequest {
    return new GetCreditsRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GetCreditsRequest {
    return new GetCreditsRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GetCreditsRequest {
    return new GetCreditsRequest().fromJsonString(jsonString, options);
  }

  static equals(a: GetCreditsRequest | PlainMessage<GetCreditsRequest> | undefined, b: GetCreditsRequest | PlainMessage<GetCreditsRequest> | undefined): boolean {
    return proto3.util.equals(GetCreditsRequest, a, b);
  }
}

/**
 * @generated from message com.qapp.hermes.CreditStatusResponse
 */
export class CreditStatusResponse extends Message<CreditStatusResponse> {
  /**
   * @generated from field: int32 user_id = 1;
   */
  userId = 0;

  /**
   * @generated from field: int32 balance = 2;
   */
  balance = 0;

  constructor(data?: PartialMessage<CreditStatusResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "com.qapp.hermes.CreditStatusResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "user_id", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 2, name: "balance", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): CreditStatusResponse {
    return new CreditStatusResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): CreditStatusResponse {
    return new CreditStatusResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): CreditStatusResponse {
    return new CreditStatusResponse().fromJsonString(jsonString, options);
  }

  static equals(a: CreditStatusResponse | PlainMessage<CreditStatusResponse> | undefined, b: CreditStatusResponse | PlainMessage<CreditStatusResponse> | undefined): boolean {
    return proto3.util.equals(CreditStatusResponse, a, b);
  }
}

/**
 * @generated from message com.qapp.hermes.PurchaseRequest
 */
export class PurchaseRequest extends Message<PurchaseRequest> {
  /**
   * @generated from field: int32 user_id = 1;
   */
  userId = 0;

  /**
   * @generated from field: int32 amount = 2;
   */
  amount = 0;

  constructor(data?: PartialMessage<PurchaseRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "com.qapp.hermes.PurchaseRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "user_id", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 2, name: "amount", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): PurchaseRequest {
    return new PurchaseRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): PurchaseRequest {
    return new PurchaseRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): PurchaseRequest {
    return new PurchaseRequest().fromJsonString(jsonString, options);
  }

  static equals(a: PurchaseRequest | PlainMessage<PurchaseRequest> | undefined, b: PurchaseRequest | PlainMessage<PurchaseRequest> | undefined): boolean {
    return proto3.util.equals(PurchaseRequest, a, b);
  }
}

